name: My first Workflow 

on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Execute script personalizado
        run: |
          echo "Este é um script personalizado."
          

     
